In [580]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris 
from math import sqrt
import kmeans
from numpy.linalg import norm
from numpy.random import choice
from numpy.random import seed

In [581]:
iris = load_iris()
data = list(iris.data)
data

[array([5.1, 3.5, 1.4, 0.2]),
 array([4.9, 3. , 1.4, 0.2]),
 array([4.7, 3.2, 1.3, 0.2]),
 array([4.6, 3.1, 1.5, 0.2]),
 array([5. , 3.6, 1.4, 0.2]),
 array([5.4, 3.9, 1.7, 0.4]),
 array([4.6, 3.4, 1.4, 0.3]),
 array([5. , 3.4, 1.5, 0.2]),
 array([4.4, 2.9, 1.4, 0.2]),
 array([4.9, 3.1, 1.5, 0.1]),
 array([5.4, 3.7, 1.5, 0.2]),
 array([4.8, 3.4, 1.6, 0.2]),
 array([4.8, 3. , 1.4, 0.1]),
 array([4.3, 3. , 1.1, 0.1]),
 array([5.8, 4. , 1.2, 0.2]),
 array([5.7, 4.4, 1.5, 0.4]),
 array([5.4, 3.9, 1.3, 0.4]),
 array([5.1, 3.5, 1.4, 0.3]),
 array([5.7, 3.8, 1.7, 0.3]),
 array([5.1, 3.8, 1.5, 0.3]),
 array([5.4, 3.4, 1.7, 0.2]),
 array([5.1, 3.7, 1.5, 0.4]),
 array([4.6, 3.6, 1. , 0.2]),
 array([5.1, 3.3, 1.7, 0.5]),
 array([4.8, 3.4, 1.9, 0.2]),
 array([5. , 3. , 1.6, 0.2]),
 array([5. , 3.4, 1.6, 0.4]),
 array([5.2, 3.5, 1.5, 0.2]),
 array([5.2, 3.4, 1.4, 0.2]),
 array([4.7, 3.2, 1.6, 0.2]),
 array([4.8, 3.1, 1.6, 0.2]),
 array([5.4, 3.4, 1.5, 0.4]),
 array([5.2, 4.1, 1.5, 0.1]),
 array([5.

### Initializing number of clusters and iterations

In [582]:
k = 3 
max_iteration = 500

### Defining each distance formula

In [583]:
# helper function
def dot_prod(v1, v2):
    return sum(a * b for a, b in zip(v1, v2))

# Euclidean Distance
def euclid_dist(v1, v2):
    dis = sum((v1 - v2)**2)**0.5
    return dis

# Cosine Similarity
def cosine_sim_dist(v1, v2): 
#     v1 = list(v1)
#     v2 = list(v2)
    #get magnitude of each vector
    mag_v1 = sqrt(dot_prod(v1, v1))
    mag_v2 = sqrt(dot_prod(v2, v2))
    
    return dot_prod(v1, v2) / (mag_v1 * mag_v2 + .00000000001)
    
# Jaccard Similarity
def jaccard_dist(v1, v2):
    # gets min of v1 and v2 pairwise
    min_sum = sum([min(a,b) for a,b in zip(v1, v2)])
    # gets max of v1 and v2 pairwise
    max_sum = sum([max(a,b) for a,b in zip(v1, v2)])     
    return min_sum / max_sum

### Defining the K-mean algorithm

In [599]:
def KMean(data, k , max_iteration, dist_eq = 'euclid'):
    
    centroids = {}
    for i in range(k):
        centroids[i] = data[choice(range(len(data)))]
#         data[choice(len(data))]    
    classes = {}
    
    for iteration in range(max_iteration):
        classes = {}
        
        for class_key in range(k):
            classes[class_key] = []
            
        for point in data:
            distance = []
            for centroid in centroids:
                if dist_eq == 'euclid':
                    dis = euclid_dist(point, centroids[centroid])
                elif dist_eq == 'jaccard':
                    dis = 1 - jaccard_dist(point, centroids[centroid])
                else: 
                    dis = 1 - cosine_sim_dist(point, centroids[centroid])
                    
                    
                distance.append(dis)
            
            min_dist = min(distance)
            min_dist_idx = distance.index(min_dist)
            classes[min_dist_idx].append(point)
            
        old_centroid = dict(centroids)
        
        for class_key in classes:
            class_data = classes[class_key]
            new_centroid = np.mean(class_data, axis=0)
            centroids[class_key] = new_centroid
            
            
        fine = True
        
        for centroid in old_centroid:
            old_cent = old_centroid[centroid]
            current = centroids[centroid]
            
            if np.sum((current - old_cent)/ old_cent * 100) > 0.001:
                fine = False
                
                
        if fine:
            break
            
    return centroids, classes
            
            

In [600]:
centroids, classes = KMean(data, k, max_iteration, dist_eq='euclid')

In [601]:
centroids, classes

({0: array([7.08695652, 3.12608696, 6.01304348, 2.14347826]),
  1: array([5.01818182, 3.33090909, 1.63090909, 0.31636364]),
  2: array([6.07638889, 2.82638889, 4.6625    , 1.57222222])},
 {0: [array([6.3, 3.3, 6. , 2.5]),
   array([7.1, 3. , 5.9, 2.1]),
   array([6.5, 3. , 5.8, 2.2]),
   array([7.6, 3. , 6.6, 2.1]),
   array([7.3, 2.9, 6.3, 1.8]),
   array([6.7, 2.5, 5.8, 1.8]),
   array([7.2, 3.6, 6.1, 2.5]),
   array([6.8, 3. , 5.5, 2.1]),
   array([7.7, 3.8, 6.7, 2.2]),
   array([7.7, 2.6, 6.9, 2.3]),
   array([6.9, 3.2, 5.7, 2.3]),
   array([7.7, 2.8, 6.7, 2. ]),
   array([6.7, 3.3, 5.7, 2.1]),
   array([7.2, 3.2, 6. , 1.8]),
   array([7.2, 3. , 5.8, 1.6]),
   array([7.4, 2.8, 6.1, 1.9]),
   array([7.9, 3.8, 6.4, 2. ]),
   array([7.7, 3. , 6.1, 2.3]),
   array([6.3, 3.4, 5.6, 2.4]),
   array([6.9, 3.1, 5.4, 2.1]),
   array([6.7, 3.1, 5.6, 2.4]),
   array([6.8, 3.2, 5.9, 2.3]),
   array([6.7, 3.3, 5.7, 2.5])],
  1: [array([5.1, 3.5, 1.4, 0.2]),
   array([4.9, 3. , 1.4, 0.2]),
   arr

In [513]:
compute_sse(centroids, classes)

92.21268218623479

### Computing SSE for each distance measure

In [141]:
def compute_sse(centroids, classes):
    sse = 0
    for c in classes:
        for point in classes[c]:
            sse += np.square(norm(point - centroids[c]))
    return sse

##### SSE for Euclidean

In [516]:
#Solve for SSE
centroids, classes = KMean(data, k, max_iteration, dist_eq='euclid')
compute_sse(centroids, classes)

78.85566582597731

##### SSE for Cosine

In [155]:
centroids, classes = KMean(data, k, max_iteration, dist_eq='cosine')
compute_sse(centroids, classes)

94.05184848484849

##### SSE for Jaccard

In [172]:
centroids, classes = KMean(data, k, max_iteration, dist_eq='jaccard')
compute_sse(centroids, classes)

588.7835618052625

### Calculating Accuracy 

In [427]:
def compute_acc(data, target_data, classes):
    data = [list(x) for x in data]
    correct = 0
    targets = []
    
    # outputs list for analysis
    for c in classes:
        for point in classes[c]:
            target_idx = [i for i, x in enumerate(data) if x == list(point)]
            targets.append(list((c, point, iris.target[target_idx][0])))
    
    # get count for correctly classified
    for el in targets:
        if el[0] == el[-1]:
            correct += 1
        else:
            continue
     
    return correct / len(data)

In [518]:
compute_acc(data, iris.target, classes)

0.44666666666666666

#### Accuracy using Euclidean

In [525]:
centroids, classes = KMean(data, k, max_iteration, dist_eq='euclid')
compute_acc(data, iris.target, classes)

0.8866666666666667

#### Accuracy using Cosine

In [536]:
centroids, classes = KMean(data, k, max_iteration, dist_eq='cosine')
compute_acc(data, iris.target, classes)

0.5533333333333333

#### Accuracy using Jaccard

In [443]:
centroids, classes = KMean(data, k, max_iteration, dist_eq='jaccard')
compute_acc(data, iris.target, classes)

0.52

# K-means using different stop criteria

In [672]:
def KMean(data, k , max_iteration, dist_eq = 'euclid', stop_criteria = 'preset'):
    
    centroids = {}
    for i in range(k):
        centroids[i] = data[choice(range(len(data)))]
#         data[choice(len(data))]    
    classes = {}
    sse_ls = []
    
    for iteration in range(max_iteration):
        classes = {}
        
        for class_key in range(k):
            classes[class_key] = []
            
        for point in data:
            distance = []
            for centroid in centroids:
                if dist_eq == 'euclid':
                    dis = euclid_dist(point, centroids[centroid])
                elif dist_eq == 'jaccard':
                    dis = 1 - jaccard_dist(point, centroids[centroid])
                else: 
                    dis = 1 - cosine_sim_dist(point, centroids[centroid])
                    
                    
                distance.append(dis)
            
            min_dist = min(distance)
            min_dist_idx = distance.index(min_dist)
            classes[min_dist_idx].append(point)
            
        old_centroid = dict(centroids)
        
        for class_key in classes:
            class_data = classes[class_key]
            new_centroid = np.mean(class_data, axis=0)
            centroids[class_key] = new_centroid
        
        # calculating SSE
        sse = compute_sse(centroids, classes)
        sse_ls.append(sse)    
            
        stop = False
        
        #Different stop criteria:
        if stop_criteria == 'no_change_centroid':
            #compare previous centroid with current centroid
            #if equal to certain decimal, stop = True
            change = True
            for centroid in old_centroid:
                old_cent = old_centroid[centroid]
                current = centroids[centroid]
                if list(old_cent) == list(current):
                    change = False
                    
            #if no change in centroid, then iterations stop      
            if change == False:
                stop = True
                
        elif stop_criteria == 'sse_increase':
            #compare previous sse with current sse
            #if previous_sse < current_sse, stop = True
            if sse_ls[-1] is None:
                continue
            else:
                previous_sse = sse_ls[-1]
                current_sse = sse

            if previous_sse < current_sse:
                stop = True
        else: 
            continue  
       
        if stop:
            break   
    return centroids, classes
            
            

#### Euclidean using no change in centroid stop condition 

In [621]:
centroids, classes = KMean(data, k, max_iteration, dist_eq='euclid', stop_criteria='no_change_centroid')
compute_acc(data, iris.target, classes)

0.8933333333333333

#### Euclidean using sse increase stop condition

In [647]:
centroids, classes = KMean(data, k, max_iteration, dist_eq='euclid', stop_criteria='sse_increase')
compute_acc(data, iris.target, classes)

0.8866666666666667

#### Euclidean using preset iteration stop condition

In [746]:
max_iteration = 100
centroids, classes = KMean(data, k, max_iteration, dist_eq='euclid', stop_criteria='preset')
compute_acc(data, iris.target, classes)

0.5733333333333334

#### Cosine using no change in centroid stop condition 

In [697]:
centroids, classes = KMean(data, k, max_iteration, dist_eq='cosine', stop_criteria='no_change_centroid')
compute_acc(data, iris.target, classes)

0.86

#### Cosine using sse increase stop condition

In [705]:
centroids, classes = KMean(data, k, max_iteration, dist_eq='cosine', stop_criteria='sse_increase')
compute_acc(data, iris.target, classes)

0.5

#### Cosine using preset iteration stop condition

In [715]:
max_iteration = 100
centroids, classes = KMean(data, k, max_iteration, dist_eq='cosine', stop_criteria='preset')
compute_acc(data, iris.target, classes)

0.9733333333333334

#### Jaccard using no change in centroid stop condition 

In [723]:
centroids, classes = KMean(data, k, max_iteration, dist_eq='jaccard', stop_criteria='no_change_centroid')
compute_acc(data, iris.target, classes)

0.88

#### Jaccard using sse increase stop condition

In [729]:
centroids, classes = KMean(data, k, max_iteration, dist_eq='jaccard', stop_criteria='sse_increase')
compute_acc(data, iris.target, classes)

0.8933333333333333

#### Jaccard using preset iteration stop condition

In [738]:
max_iteration = 100
centroids, classes = KMean(data, k, max_iteration, dist_eq='cosine', stop_criteria='preset')
compute_acc(data, iris.target, classes)

0.5133333333333333